#!/bin/sh

#the user and home directories are on a green to red gradient indicating cpu temp and ram use respectively
#the @ symbol is blue normally, changes to purple in a repo. also makes use of the git branch script
#the prompt arrow changes colour hourly based on the time of day

PATH="$PATH:$PROMPT_BASE_DIR/bin"

export GIT_PROMPT=1

GIT_BRANCH=$(git_prompt.sh)
SSH=$(`env | grep SSH`)


if [ -n "$SSH" ]; then
	AT="\e[38;5;57m"
else
	AT="\e[38;5;81m"
fi

echo "\[$(cpu_temp_colourizer.sh)\]\u\[\e[0m\] \[$AT\]@\[\e[0m\] \[$(ram_usage_colourizer.sh)\]\w/\[\e[0m\]$GIT_BRANCH\n \[$(time_of_day_colourizer.sh)\]==>\[\e[0m\] "
