#!/bin/sh

#the user and home directories are on a green to red gradient indicating cpu temp and ram use respectively
#the @ symbol is blue normally, changes to purple in a repo. also makes use of the git branch script
#the prompt arrow changes colour hourly based on the time of day

PATH="$PATH:$PROMPT_BASE_DIR/bin"
export GIT_PROMPT=1

echo "\[$(temp.sh)\]\u\[\e[0m\] \[$(isgit.sh)\]@\[\e[0m\] $(ram.sh)\w/\[\e[0m\]$(git_prompt.sh)$ERROR\n \[$(time.sh)\]==>\[\e[0m\] "
